name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [production, staging, development]

    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        run: python3 --version
        
      - name: Checkout code
        run: git --version
