name : First workflow
on : [push]

jobs:
  my-first-actions:
    runs-on: ubuntu-latest
    steps:
     - name : run echo command
       run: echo "first action rakesh"
     - name : run install command
       run : sudo apt-get update -y
  my-parellel-job1:
     needs: my-first-actions
     runs-on: ubuntu-latest
     steps:
       - name : check python version
         run: python3 --version
       - name : install maven
         run : sudo apt-get install maven -y
  my-parellel-job2:
      runs-on: ubuntu-latest
      steps:
        - name : check python verison again
          run: python3 --version
        - name : echo variables defined in ui
          run : |
           echo "$COLLEGE"
           echo "$FAMILY"
