name : First workflow
on : [push]
env:
  COMPANY : accenture

jobs:
  my-first-actions:
    runs-on: ubuntu-latest
    steps:
     - name : run echo command
       run: echo "first action rakesh"
     - name : run install command
       run : sudo apt-get update -y
  my-parellel-job1:
     needs: my-first-actions
     runs-on: ubuntu-latest
     steps:
       - name : check python version
         run: python3 --version
       - name : install maven
         run : sudo apt-get install maven -y
       - name : echo workflow level env
         run : echo $COMPANY
  my-parellel-job2:
      runs-on: ubuntu-latest
      env:
        COMPANY: ustglobal
        COLLEGE : ${{ vars.COLLEGE }} # Actions secrets and variables -> Repository variables/Environment variables
        BROTHER: ${{ vars.FAMILY }}
      steps:
        - name : check python verison again
          run: python3 --version
        - name : overide env on job level
          run : echo "$COMPANY"
        - name : echo default varibles
          run : echo "$GITHUB_REPOSITORY_OWNER"
        - name : echo repo vars
          run : echo "$COLLEGE"
        - name : echo repo ENV vars
          run :  echo "The value of FAMILY is $FAMILY"

          
