name: Deploy

on:
  push:
    branches:
      - master
      - main
      - prod
      - uat
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'

    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        run: python3 --version
        
      - name: Checkout code
        run: git --version



