name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [production, staging, development]

    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        run: python3 --version
