name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [production, staging, development]

    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to ${{ matrix.environment }}
        env:
          API_KEY: ${{ secrets[matrix.environment | toUpperCase() + '_API_KEY'] }}
        run: |
          echo "Deploying to ${{ matrix.environment }} environment"
          # Add your deployment commands here
          # Example: npm run deploy -- --env=${{ matrix.environment }}
